import axios from "axios";
import { useEffect } from "react";
import Head from "next/head";
import Header from "../../components/Header";
import Footer from "../../components/Footer";
import Post from "../../components/Post";
import { useRouter } from "next/router";

export async function getStaticProps(context) {
  const { params } = context;

  const res = await fetch(
    `https://dev113442.service-now.com/api/720824/devalexsantos/posts/${params.slug}`
  );
  const individualPost = await res.json();

  return {
    props: {
      individualPost,
    },

    revalidate: 30,
  };
}

export async function getStaticPaths() {
  const slug = await fetch(
    "https://dev113442.service-now.com/api/720824/devalexsantos/posts"
  );

  const data = await slug.json();

  return {
    paths: data.result.posts.map((posts) => {
      return {
        params: {
          id: posts.id,
          slug: posts.slug,
        },
      };
    }),
    fallback: true,
  };
}

export default function Home({ individualPost }) {
  const router = useRouter();
  const data = individualPost.result;

  const navigation = [
    { name: "Início", href: "/", current: false },
    { name: "Posts", href: "#", current: true },
    { name: "Works", href: "#", current: false },
    { name: "Contato", href: "/contato", current: false },
  ];

  if (router.isFallback) {
    return <div>Loading...</div>;
  }

  return (
    <div>
      <Head>
        <title>Alex Santos - ServiceNow Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header info={data} navigation={navigation} />
        <Post post={data} />
        <Footer info={data} />
      </main>
    </div>
  );
}
