import axios from "axios";
import { useEffect } from "react";
import Head from "next/head";
import Header from "../components/Header";
import Profile from "../components/Profile";
import Content from "../components/Content";

export async function getStaticProps() {
  const res = await fetch(
    "https://dev113442.service-now.com/api/720824/devalexsantos"
  );
  const personalInfo = await res.json();

  return {
    props: {
      personalInfo,
    },

    revalidate: 30,
  };
}

export default function Contato({ personalInfo }) {
  const data = personalInfo.result.info;

  const navigation = [
    { name: "Início", href: "/", current: false },
    { name: "Posts", href: "#", current: false },
    { name: "Works", href: "#", current: false },
    { name: "Contato", href: "/contato", current: true },
  ];

  return (
    <div>
      <Head>
        <title>Alex Santos - Contato</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header info={data} navigation={navigation} />
        <Profile info={data} />
        <h1 className="text-center">Contato:</h1>
      </main>
    </div>
  );
}
